# Generated by Django 5.0.2 on 2024-04-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show_cars", "0002_rename_bland_car_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
